<?php

return [
    'platform' => [
        'windows nt 10.0' => 'Windows 10',
        'windows nt 6.3' => 'Windows 8.1',
        'windows nt 6.2' => 'Windows 8',
        'windows nt 6.1' => 'Windows 7',
        'windows nt 6.0' => 'Windows Vista',
        'windows' => 'Unknown Windows OS',
        'os x' => 'Mac OS X',
        'intel mac' => 'Intel Mac',
        'linux' => 'Linux',
        'debian' => 'Debian',
        'sunos' => 'Sun Solaris',
        'freebsd' => 'FreeBSD',
        'netbsd' => 'NetBSD',
        'bsdi' => 'BSDi',
        'openbsd' => 'OpenBSD',
        'aix' => 'AIX',
        'unix' => 'Unknown Unix OS',
    ],
    'browser' => [
        'Opera' => 'Opera',
        'Edge' => 'Edge',
        'MSIE' => 'Internet Explorer',
        'Internet Explorer' => 'Internet Explorer',
        'Firefox' => 'Firefox',
        'Chrome' => 'Chrome',
        'Safari' => 'Safari',
        'CFNetwork' => 'Safari', // Core Foundation for OSX, WebKit/Safari
        'Konqueror' => 'Konqueror',
        'Mozilla' => 'Mozilla',
        'lynx' => 'Lynx',
        'links' => 'Links',
    ],
    'mobile' => [
        'opera mini' => 'Opera Mini',
        'operamini' => 'Opera Mini',
        'nokia' => 'Nokia',
        'ericsson' => 'Ericsson',
        'blackBerry' => 'BlackBerry',
        'motorola' => 'Motorola',
        'iphone' => 'iPhone',
        'ipad' => 'iPad',
        'ipod' => 'iPod',
        'android' => 'Android',
    ],
    'robot' => [
        'googlebot' => 'Googlebot',
        'msnbot' => 'MSNBot',
        'facebookexternalhit' => 'Facebook',
        'slurp' => 'Inktomi Slurp',
        'yahoo' => 'Yahoo',
        'askjeeves' => 'AskJeeves',
        'fastcrawler' => 'FastCrawler',
        'infoseek' => 'InfoSeek Robot 1.0',
        'lycos' => 'Lycos',
    ],
];
